const productos= [
    {id: 1,
      nombre: "Eco-Cepillo Dental",
      descripcion: "Cepillo de bambú biodegradable con cerdas de carbón activado.",
      precio: 5.99,
      cantidad: 100,
      imagen: src="img/1.jpg",
    },
    {
      id: 2,
      nombre: "Botella de Agua Auto-Limpiable",
      descripcion: "Botella con luz UV integrada para purificar el agua.",
      precio: 29.99,
      cantidad: 50,
      imagen: src="img/2.jpg",
    },
    {
      id: 3,
      nombre: "Pluma de Borrado Instantáneo",
      descripcion: "Pluma que borra tinta con un solo clic, sin dejar rastro.",
      precio: 9.99,
      cantidad: 200,
      imagen: src="img/3.jpg",
    },
    {
      id: 4,
      nombre: "Mochila Solar Cargadora",
      descripcion: "Mochila con panel solar integrado para cargar dispositivos móviles.",
      precio: 79.99,
      cantidad: 25,
      imagen: src="img/4.jpg",
    },
    {
      id: 5,
      nombre: "Audífonos de Traducción Simultánea",
      descripcion: "Audífonos que traducen idiomas en tiempo real.",
      precio: 149.99,
      cantidad: 10,
      imagen: src="img/5.jpg",
    },
    {
      id: 6,
      nombre: "Almohada de Masaje Inteligente",
      descripcion: "Almohada que se adapta a tu cuerpo y proporciona masajes personalizados.",
      precio: 69.99,
      cantidad: 30,
      imagen: src="img/6.jpg",
    },
    {
      id: 7,
      nombre: "Lámpara de Escritorio con Carga Inalámbrica",
      descripcion: "Lámpara que carga tu teléfono mientras ilumina tu espacio.",
      precio: 49.99,
      cantidad: 40,
      imagen: src="img/7.jpg",
    },
    {
      id: 8,
      nombre: "Guantes de Realidad Virtual Táctiles",
      descripcion: "Guantes que te permiten sentir objetos en la realidad virtual.",
      precio: 199.99,
      cantidad: 5,
      imagen: src="img/8.jpg",
    },
    {
      id: 9,
      nombre: "Cámara de Seguridad con Reconocimiento Facial",
      descripcion: "Cámara que identifica a las personas y envía alertas.",
      precio: 89.99,
      cantidad: 15,
      imagen: src="img/9.jpg",
    },
    {
      id: 10,
      nombre: "Robot Aspirador con Mapeo Inteligente",
      descripcion: "Aspirador que limpia tu casa de forma autónoma, creando mapas.",
      precio: 249.99,
      cantidad: 8,
      imagen: src="img/10.jpg",
    },
    {
      id: 11,
      nombre: "Bicicleta Eléctrica Plegable",
      descripcion: "Bicicleta que se pliega para facilitar su transporte.",
      precio: 599.99,
      cantidad: 3,
      imagen: src="img/11.jpg",
    },
    {
      id: 12,
        nombre: "Reloj Inteligente con Monitor de Sueño",
        descripcion: "Reloj que analiza tu sueño y te ayuda a mejorarlo.",
        precio: 129.99,
        cantidad: 20,
        imagen: src="img/12.jpg",
      },
      {
        id: 13,
        nombre: "Impresora 3D de Bolsillo",
        descripcion: "Impresora que cabe en tu bolsillo y te permite imprimir objetos pequeños.",
        precio: 349.99,
        cantidad: 2,
        imagen: src="img/13.jpg",
      },
      {
        id: 14,
        nombre: "Kit de Cultivo Hidropónico Casero",
        descripcion: "Kit para cultivar tus propias hierbas y verduras en casa.",
        precio: 59.99,
        cantidad: 25,
        imagen: src="img/14.jpg",
      },
      {
        id: 15,
        nombre: "Drone con Cámara 4K y Estabilización",
        descripcion: "Drone que graba videos y toma fotos de alta calidad.",
        precio: 499.99,
        cantidad: 6,
        imagen: src="img/15.jpg",
      },
    ];

    function agregarAlCarrito(productId) {
      localStorage.setItem("productos", JSON.stringify(productos));
    }

    //prepa perdon mi cerebro no cerebreo mas.